Add generic typing for renderer plugins
pixijs/pixi-typescript pull request #178
Opened 2017-07-28 12:46 UTC by giraluna

Allow user to specify type of plugins available for a renderer.

Defaults to the [plugins listed in the docs.](http://pixijs.download/release/docs/PIXI.WebGLRenderer.html#plugins) Users who excluded plugins in a custom build or will register their own plugins should define a custom type instead.

Usage:
```
type CustomPlugins = {
  accessibility: PIXI.accessibility.AccessibilityManager;
  extract: PIXI.extract.CanvasExtract;
};

const customRenderer = new PIXI.WebGLRenderer<CustomPlugins>();
customRenderer.plugins.interaction.mouseMove = e => {}; // error

const defaultRenderer = new PIXI.WebGLRenderer();
defaultRenderer.plugins.interaction.onPointerMove = e => {}; // no problemo
defaultRenderer.plugins.picture; // error: no such property
```

2017-07-28 12:49 UTC, andrewstart approved these changes
Came here to suggest using defaults, but you are already on top of it.

2017-07-28 12:50 UTC, ivanpopelyshev requested changes
I have better idea. Make it an interface and let people to expand it!

```
export interface WebGLRendererPlugins {
    [key: string]: any;
    interaction: InteractionManager;
}
```

Somewhere else:

```
declare module PIXI {
    export interface WebGLRendererPlugins {
        picture: PictureRenderer;
    }
}
```

Usage:

```
renderer.plugins.custom; //error
renderer.plugins['custom']; //ok
renderer.plugins.picture; // OK, it has a type!
```

That is the part of my TS conversion, https://github.com/gameofbombs/gobi

Interface merging is a very powerful thing, it helps a lot.

2017-07-28 12:54 UTC, ivanpopelyshev commented
I can make another PR for it.

2017-07-28 13:13 UTC, giraluna commented
@ivanpopelyshev that actually makes more sense considering how plugins are registered to the renderer class and not per instance.

But can you use declaration merging to both get the default plugins as default and the ability to remove default plugins for custom builds? The user shouldn't have to define defaults and I don't think something like `RendererPlugins {interaction: undefined}` works via merging.

2017-07-28 13:59 UTC, giraluna commented
You might be able to do it with https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458. Something like:
```
export interface CustomRendererPlugins {

}
export class Renderer {
  plugins: Overwrite<DefaultRendererPlugins, CustomRendererPlugins>
}
```
The user can then define `CustomRendererPlugins` to both add and remove plugins:
```
declare global {
  namespace PIXI {
    export interface CustomRendererPlugins {
      interaction: undefined;
      picture: PictureRenderer;
    }
  }
}
```

2017-07-28 15:06 UTC, giraluna commented
Pushed an interface merging based version. You can't directly overwrite properties with interface merging but turns out derived interfaces can overwrite their parents'. That means there's no need for the `Overwrite<>` stuff from my last comment.
Usage:
```
declare global {
  namespace PIXI {
    export interface RendererPlugins {
      interaction: void;
    }
    export interface WebGLRendererPlugins {
      picture: PictureRenderer;
    }
  }
}
```

2017-07-28 15:23 UTC, ivanpopelyshev approved these changes
Please remove single line at 904. Everything else looks fine.

2017-07-31 09:02 UTC, ivanpopelyshev commented
@clark-stevenson please look here!

2017-07-31 09:44 UTC, merged

2017-07-31 09:45 UTC, clark-stevenson commented
Thanks guys 👍